import mainlogo from "./mainLogo.svg"
import UkIcon from "./unitedkingdom.png"
import SaLogo from "./saudiarabia.png"
import mainlogo2 from "./mainLogo2.svg"
import authbg from "./authBg.svg"
import hero1 from "./hero1.svg"
import hero2 from "./hero2.jpeg"
import requestoffer from "./requestoffer.svg"
import askservice from "./askservice.svg"
import chooselawyer from "./chooselawyer.svg"
import consultantchat from "./consultantchat.svg"
import calllawyer from "./calllawyer.svg"
import asklawyer from "./asklawyer.svg"
import contactus from "./contactus.svg"
import iphone from "./iPhone.svg"
import aboutus from "./aboutus.svg"
import aboutusBg from "./aboutBg.jpg"
export {mainlogo , UkIcon ,SaLogo ,mainlogo2 ,authbg ,hero1 ,hero2 ,requestoffer ,askservice ,chooselawyer ,consultantchat ,calllawyer ,asklawyer ,contactus ,iphone ,aboutus ,aboutusBg} 